# Workflow name
name: "Chromatic"

# Event for the workflow
on:
  push:
    branches: [ main ]
    paths:
      - 'apps/docs/**'
      - 'packages/ui/**'

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: npm install
      - name: Install build
        run: npx turbo run build --scope='docs' --include-dependencies
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          storybookBuildDir: apps/docs/storybook-static
          storybookBaseDir: apps/docs/ui
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          exitOnceUploaded: true